server:
  port: 8082

spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://localhost:3307/db_reservation
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost